#!/usr/bin/env python
import sys
import glob
import os
import subprocess

filenames = sys.argv[1:]

if not filenames:
    filenames += glob.glob('*.JPG')
    filenames += glob.glob('*.jpg')
    filenames += glob.glob('*.PNG')
    filenames += glob.glob('*.png')
    filenames += glob.glob('*.GIF')
    filenames += glob.glob('*.gif')
    for arg in filenames[:]:
        if '.small.' in arg or '.thumb.' in arg:
            filenames.remove(arg)
    filenames.sort()

for fn in filenames:
    print(fn)
    subprocess.call(['exiftran', '-a', '-i', fn])
    
