#!/usr/bin/env python
import sys
import glob
import os
import subprocess

filenames = sys.argv[1:]

if not filenames:
    filenames += glob.glob('*.JPG')
    filenames += glob.glob('*.jpg')
    filenames += glob.glob('*.PNG')
    filenames += glob.glob('*.png')
    filenames += glob.glob('*.GIF')
    filenames += glob.glob('*.gif')
    for arg in filenames[:]:
        if '.small.' in arg or '.thumb.' in arg or '.little.' in arg:
            filenames.remove(arg)

for fn in filenames:
    print(fn)
    base, extn = os.path.splitext(fn)
    fn2 = base + os.extsep + 'small' + extn
    if not os.path.exists(fn2):
        subprocess.call(['convert', fn, '-scale', '800', fn2])
    fn2 = base + os.extsep + 'thumb' + extn
    if not os.path.exists(fn2):
        subprocess.call(['convert', fn, '-scale', '200', fn2])

